### PR TITLE
Sucrose Logo & Property Localization

### PR DESCRIPTION
**Pull request by Taiizor**
Localization support was added to theme customizations after Sucrose v24.6.24.0.

This pull request also includes changes for localization. Translations have been made for English (EN), German (DE), Spanish (ES), French (FR), Polish (PL), and Turkish (TR) languages. This is clearly visible in the images below.

Sucrose-EN
Sucrose-DE
Sucrose-ES
Sucrose-FR
Sucrose-PL
Sucrose-TR

### CODE REVIEW

**Comment by IPdotSetAF** [comment]
Don't forget to add ur logo in the readme file

**Comment by Taiizor** [comment]
> Don't forget to add ur logo in the readme file

Oh my god, I don't know where my mind was (;

**Review by IPdotSetAF — APPROVED** [review]

**Comment by Taiizor** [comment]
@IPdotSetAF Can you change the 'Sucrose' text below to 'sucrose'?

https://github.com/IPdotSetAF/NeoMatrix/blob/master/js/index.js#L634

**Comment by IPdotSetAF** [comment]
> @IPdotSetAF Can you change the 'Sucrose' text below to 'sucrose'?
> 
> https://github.com/IPdotSetAF/NeoMatrix/blob/master/js/index.js#L634

Ok, sure 👌

**Pull request merged**
