### PR TITLE
38 iframe enhancement

### PR DESCRIPTION
**Pull request by IPdotSetAF**
totall rework for loading properties from:
   - iframe
   - Wallpaper Engine
   - Sucrose Wallpaper Engine

other changes
   - moved helper functions to separate JS file
   - added object mapper

### CODE REVIEW

**Comment by IPdotSetAF** [comment]
test scenarios:
   - [x] iframe
   - [x] WE
   - [ ] Sucrose WE

**Comment by IPdotSetAF** [comment]
hey @Taiizor , could you give me a hand with testing this branch?
i've made some changes to the property loading logic and I need to test it before publishing.
my version of sucrose seems old and doesn't run the current version of this wallpaper,
I tried updating sucrose but its taking forever to download the release.

these properties especially:
image

**Comment by Taiizor** [comment]
> hey @Taiizor , could you give me a hand with testing this branch? i've made some changes to the property loading logic and I need to test it before publishing. my version of sucrose seems old and doesn't run the current version of this wallpaper, I tried updating sucrose but its taking forever to download the release.
> 
> these properties especially: image


Can you manually reinstall it from the link below?

https://github.com/Taiizor/Sucrose/releases/download/v24.9.11.0/Sucrose_Bundle_.NET_Framework_4.8_x64_24.9.11.0.exe

**Comment by IPdotSetAF** [comment]
thanks @Taiizor, the new link downloaded way faster and installed perfectly.

**Comment by Taiizor** [comment]
> I tried updating sucrose but its taking forever to download the release.

Can you generate a log file from within the application and send it to me?

Bug
Report

**Comment by IPdotSetAF** [comment]
well i removed the last version, but i hope the logs persisted 
[sucrose_log_20240919_222314.zip](https://github.com/user-attachments/files/17065030/sucrose_log_20240919_222314.zip)

**Comment by Taiizor** [comment]
> well i removed the last version, but i hope the logs persisted [sucrose_log_20240919_222314.zip](https://github.com/user-attachments/files/17065030/sucrose_log_20240919_222314.zip)

Your log files have been saved. I’m using a third-party [downloader](https://github.com/bezzad/Downloader) package, and I think the issue might be related to that.

**Comment by Taiizor** [comment]
By the way, I didn't see any issues with the changes you made. It seemed to be working fine.

**Comment by IPdotSetAF** [comment]
> By the way, I didn't see any issues with the changes you made. It seemed to be working fine.

well I tested and the properties that are not listed in my code are not working.

**Pull request merged**
