### PR TITLE
Sucrose Compatibility

### PR DESCRIPTION
**Pull request by Taiizor**
Sucrose Compatibility #15

Would it be a problem if I didn't create a new branch?

### CODE REVIEW

**Comment by IPdotSetAF** [comment]
> Would it be a problem if I didn't create a new branch?

would make later updating simpler on your side, doesn't affect me at all.

**Comment by Taiizor** [comment]
> > Would it be a problem if I didn't create a new branch?
> 
> would make later updating simpler on your side, doesn't affect me at all.

Great, then there's no problem (:

**Comment by IPdotSetAF** [comment]
@Taiizor Is there any property or flag inside the window that i can check to make sure that we are running inside SucroseWE?

**Comment by Taiizor** [comment]
> @Taiizor Is there any property or flag inside the window that i can check to make sure that we are running inside SucroseWE?

Actually, there's no such thing, but the User Agent content contains `Sucrose/X.Y (Wallpaper Engine) SucroseWebKit`. You can detect it using this.

Sucrose

**Pull request merged**
